### PR TITLE
Conditional backport packages

### LINKED ISSUE #6: Can't install pyquil 2 on py37
I think some of the backfill packages need to be selectored out

### PR DESCRIPTION
**Pull request by mpharrigan**
fixes gh-6

### CODE REVIEW

**Comment by mpharrigan** [comment]
@conda-forge-admin please rerender

**Comment by mpharrigan** [comment]
@conda-forge-admin please rerender

**Comment by mpharrigan** [comment]
why is it trying to peg `sqlite==3.13`

**Comment by mpharrigan** [comment]
@conda-forge-admin please rerender

**Comment by mpharrigan** [comment]
@conda-forge/help-python I'm completely baffled by why *none* of the builds are working. Any ideas?

**Comment by mpharrigan** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
So it's a very bad idea to make branches on the feedstock repo. Every one of these builds does a release.

**Comment by mpharrigan** [comment]
good thing all the builds were so broken

**Pull request closed without merging**
